// Generated by scripts/generate-image-variants.mjs — do not edit.
/** Widths of the smaller copies that exist next to each large photo (`name-<width>.webp`). */
export const IMAGE_VARIANTS: Readonly<Record<string, readonly number[]>> = {
  'images/bqes/gallery/annual-sports-1.webp': [480],
  'images/bqes/gallery/annual-sports-2.webp': [480, 960, 1440],
  'images/bqes/gallery/annual-sports-3.webp': [480, 960],
  'images/bqes/gallery/annual-sports-4.webp': [480, 960],
  'images/bqes/gallery/annual-sports-5.webp': [480, 960],
  'images/bqes/gallery/annual-sports-6.webp': [480, 960],
  'images/bqes/gallery/annual-sports-7.webp': [480, 960],
};
